services:
  swoop_hook.registry.hooks:
    class: Swoop\Bundle\HookBundle\Registry\HooksRegistry
    public: true

  swoop_hook.hooks_processor.action:
    class: Swoop\Bundle\HookBundle\Processor\Chain\Element\ActionHooksProcessorChainElement
    calls:
      - [setSuccessor, ['@swoop_hook.hooks_processor.filter']]

  swoop_hook.hooks_processor.filter:
    class: Swoop\Bundle\HookBundle\Processor\Chain\Element\FilterHooksProcessorChainElement

  swoop_hook.hooks_processor.main:
    parent: swoop_hook.hooks_processor.action
    public: true