services:
  swoop_hook.registry.hooks:
    class: Swoop\Bundle\HookBundle\Registry\HooksRegistry
    public: true

  swoop_hook.hooks_registrator.action:
    class: Swoop\Bundle\HookBundle\Registrator\Chain\Element\ActionHooksRegistratorChainElement
    calls:
      - [setSuccessor, ['@swoop_hook.hooks_registrator.filter']]

  swoop_hook.hooks_registrator.filter:
    class: Swoop\Bundle\HookBundle\Registrator\Chain\Element\FilterHooksRegistratorChainElement

  swoop_hook.hooks_registrator.main:
    parent: swoop_hook.hooks_registrator.action
    public: true