services:
  swoop_menu.processor.admin_menu_pages:
    class: 'Swoop\Bundle\MenuBundle\Processor\AdminMenuPagesProcessor'
    public: true
    arguments:
      - '@swoop_page.registry'

  swoop_menu.processor.admin_bar_nodes:
    class: 'Swoop\Bundle\MenuBundle\Processor\AdminBarNodesProcessor'
    public: true

  swoop_menu.registry.admin_menu_pages:
    class: 'Swoop\Bundle\MenuBundle\Registry\MenuElementsRegistry'
    public: true

  swoop_menu.registry.admin_bar_nodes:
    class: 'Swoop\Bundle\MenuBundle\Registry\MenuElementsRegistry'
    public: true
