services:
    swoop_meta_box.registry.meta_boxes:
        class: 'Swoop\Bundle\MetaBoxBundle\Registry\MetaBoxesRegistry'
        public: true

    swoop_meta_box.processor.meta_boxes:
        class: 'Swoop\Bundle\MetaBoxBundle\Processor\MetaBoxesProcessor'
        public: true