services:
    swoop_media.registry.image_sizes:
        class: 'Swoop\Bundle\MediaBundle\Registry\ImageSizesRegistry'

    swoop_media.registry.mime_types:
        class: 'Swoop\Bundle\MediaBundle\Registry\MimeTypesRegistry'

    swoop_media.processor.image_sizes:
        class: 'Swoop\Bundle\MediaBundle\Processor\ImageSizesProcessor'
        public: true

    swoop_media.processor.mime_types:
        class: 'Swoop\Bundle\MediaBundle\Processor\MimeTypesProcessor'
        public: true
