services:
    swoop_media.registry.image_sizes:
        class: 'Swoop\Bundle\MediaBundle\Registry\ImageSizesRegistry'

    swoop_media.registry.mime_types:
        class: 'Swoop\Bundle\MediaBundle\Registry\MimeTypesRegistry'

    swoop_media.registrator.image_sizes:
        class: 'Swoop\Bundle\MediaBundle\Registrator\ImageSizesRegistrator'
        public: true

    swoop_media.registrator.mime_types:
        class: 'Swoop\Bundle\MediaBundle\Registrator\MimeTypesRegistrator'
        public: true
