services:
  swoop_post.registry.post_types:
    class: 'Swoop\Bundle\PostBundle\PostType\Registry\PostTypesRegistry'
    public: true

  swoop_post.registrator.post_types:
    class: 'Swoop\Bundle\PostBundle\PostType\Registrator\PostTypesRegistrator'
    public: true

  swoop_post.registry.post_statuses:
    class: 'Swoop\Bundle\PostBundle\PostStatus\Registry\PostStatusesRegistry'
    public: true

  swoop_post.registrator.post_statuses:
    class: 'Swoop\Bundle\PostBundle\PostStatus\Registrator\PostStatusesRegistrator'
    public: true