services:
    swoop_taxonomy.registry.taxonomies:
        class: 'Swoop\Bundle\TaxonomyBundle\Registry\TaxonomiesRegistry'
        public: true

    swoop_taxonomy.processor.taxonomies:
        class: 'Swoop\Bundle\TaxonomyBundle\Processor\TaxonomiesProcessor'
        public: true
