services:
    templating.name_parser:
        class: 'Swoop\Bundle\KernelBundle\Templating\TemplateNameParser'
        arguments:
            - '@kernel'

    twig.loader.filesystem:
        class: 'Twig\Loader\FilesystemLoader'

    twig:
        class: 'Twig\Environment'
        arguments:
            - '@twig.loader.filesystem'

    templating.twig.engine:
        class: 'Swoop\Bundle\KernelBundle\Templating\Twig\TwigEngine'
        arguments:
            - '@twig'
            - '@templating.name_parser'

    swoop_kernel.boot_service.composite:
        class: 'Swoop\Bundle\KernelBundle\Boot\CompositeBootService'
        public: true

    swoop_kernel.provider.plugins_versions:
        class: 'Swoop\Bundle\KernelBundle\Provider\PluginsVersionsProvider'
        public: true
        arguments:
            - '%kernel.plugins%'

    swoop_kernel.provider.plugin_name_for_class:
        class: 'Swoop\Bundle\KernelBundle\Provider\PluginNameForClassProvider'
        arguments:
            - '@kernel'

    event_dispatcher:
        class: 'Swoop\Bundle\KernelBundle\EventDispatcher\EventDispatcher'
        public: true

    runtime_object_cache:
        class: 'Swoop\Bundle\KernelBundle\Cache\RuntimeObjectCache'