services:
    swoop_request.registry.request_handlers:
        class: 'Swoop\Bundle\RequestBundle\Registry\RequestHandlersRegistry'
        public: true

    swoop_request.handlers_processor.ajax:
        class: 'Swoop\Bundle\RequestBundle\Handler\Processor\Chain\Element\AjaxRequestHandlersProcessorChainElement'
        calls:
            - ['setSuccessor', ['@swoop_request.handlers_processor.not_ajax']]

    swoop_request.handlers_processor.not_ajax:
        class: 'Swoop\Bundle\RequestBundle\Handler\Processor\Chain\Element\NotAjaxRequestHandlersProcessorChainElement'

    swoop_request.handlers_processor.main:
        parent: swoop_request.handlers_processor.ajax
        public: true