services:
  swoop_option.processor.non_site_option:
    class: 'Swoop\Bundle\OptionBundle\Processor\Chain\Element\NonSiteOptionsProcessorChainElement'
    calls:
      - ['setSuccessor', ['@swoop_option.processor.site_option']]

  swoop_option.processor.site_option:
    class: 'Swoop\Bundle\OptionBundle\Processor\Chain\Element\SiteOptionsProcessorChainElement'

  swoop_option.processor.main:
    public: true
    parent: swoop_option.processor.non_site_option

