services:
    swoop_wpcli.registry.commands:
        class: 'Swoop\Bundle\WpCliBundle\Registry\WpCliCommandsRegistry'
        public: true

    swoop_wpcli.processor.commands:
        class: 'Swoop\Bundle\WpCliBundle\Processor\WpCliCommandsProcessor'
        public: true
