services:
    swoop_rest_api.registry.rest_api.endpoints:
        class: 'Swoop\Bundle\RestApiBundle\Endpoint\Registry\RestApiEndpointsRegistry'
        public: true

    swoop_rest_api.registry.rest_api.controllers:
        class: 'Swoop\Bundle\RestApiBundle\Controller\Registry\RestApiControllersRegistry'
        public: true

    swoop_rest_api.registry.rest_api.field_providers:
        class: 'Swoop\Bundle\RestApiBundle\Field\Registry\RestApiFieldProvidersRegistry'
        public: true

    swoop_rest_api.processor.rest_api.endpoints:
        class: 'Swoop\Bundle\RestApiBundle\Endpoint\Processor\RestApiEndpointsProcessor'
        public: true

    swoop_rest_api.processor.rest_api.controllers:
        class: 'Swoop\Bundle\RestApiBundle\Controller\Processor\RestApiControllersProcessor'
        public: true

    swoop_rest_api.processor.rest_api.fields:
        class: 'Swoop\Bundle\RestApiBundle\Field\Processor\RestApiFieldsProcessor'
        public: true
